version: '3'

services:
  saas-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    networks:
      - app-net
    environment:
     PG_URL: "postgresql://postgres:postgres@saas-db:5432/nestjs-multi-tenant"
    depends_on:
      - saas-db
  saas-db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: nestjs-multi-tenant
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:

